### PR TITLE
Workaround error issue 711

### PR DESCRIPTION
**Pull request by awesomebytes**
Following discussion in https://github.com/ros/ros-overlay/issues/711 

Tested on Gentoo Prefix amd64

### CODE REVIEW

**Comment by awesomebytes** [comment]
CI failed... but this PR has nothing to do with it as you may see in the error.

**Comment by allenh1** [comment]
> CI failed... 

It always does. :/ I'll get around to fixing it at some point.

This looks fine to me.

**Comment by allenh1** [comment]
@awesomebytes does this patch need to be replicated for any other distros?

**Comment by awesomebytes** [comment]
I believe it will be needed for all distros. But I haven't tested it on any other distro yet. Tomorrow I'll hopefully setup CI for indigo and melodic and I'll be able to tell you.

**Comment by Mortazamakasaadi** [comment]
tested your patch, on ArchLinux with cmake 3.13.1 couldn't compile ros-melodic-rostime 
`CMake Error at /opt/ros/melodic/share/cpp_common/cmake/cpp_commonConfig.cmake:148 (message):
  Project 'rostime' tried to find library '-lpthread'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'cpp_common'? Did you find_package() it before the subdirectory containing
  its code is included?
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:4 (find_package)`
after patching ros-melodic-catkin and recompiling ros-melodic-cpp-common... managed to successfully compile ros-melodic-rostime.

**Comment by awesomebytes** [comment]
@allenh1 That means we need to replicate it for the other distros (at least melodic). I haven't setup CI for those yet. I'm trying to finish with desktop and desktop full on kinetic first.

**Pull request merged**
