### PR TITLE
Add a workaround for when tests are not enabled

### PR DESCRIPTION
**Pull request by awesomebytes**
Fix https://github.com/ros/ros-overlay/issues/593

### CODE REVIEW

**Comment by allenh1** [comment]
Could you please regenerate the manifest as well?

**Comment by awesomebytes** [comment]
Isn't there something else to do so the ebuild actually applies the patch?

**Comment by allenh1** [comment]
Yes, you are correct. If you just clone the overlay locally and creat the patch within it, you can run

```
cd [overlay]/ros-kinetic/ros_numpy
git add files
superflore-gen-ebuilds --only ros_numpy --ros-distro kinetic --output-repository-path [overlay]
```

And the patch will be pulled in, the ebuild update and the manifest generated.

**Comment by awesomebytes** [comment]
Done https://github.com/ros/ros-overlay/pull/597

**Comment by allenh1** [comment]
Closing in favor of #597.

**Pull request closed without merging**
