### PR TITLE
Fix ROS path to include the EPREFIX

### PR DESCRIPTION
**Pull request by awesomebytes**
So in environments like Gentoo Prefix paths are correct.

Running a recompilation right now, don't merge yet.

### CODE REVIEW

**Comment by allenh1** [comment]
Changes look great! Checking them on my docker container as well, since I don't have any of those variables changed. If that works, and yours is good, then we'll merge it. :tada:

**Comment by awesomebytes** [comment]
It works!

**Comment by allenh1** [comment]
Uh, there's still problems. Not sure what's causing this, but I'll need to fix it.

```
 # emerge ros-kinetic/ros_base 

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 148) ros-kinetic/cpp_common-0.6.9::ros-overlay
 * cpp_common-kinetic-release-0.6.9.tar.gz BLAKE2B SHA512 size ;-) ...   [ ok ]
>>> Unpacking source...
>>> Unpacking cpp_common-kinetic-release-0.6.9.tar.gz to /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work
>>> Source unpacked in /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work
>>> Preparing source in /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build"
cmake -C /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCATKIN_ENABLE_TESTING=0 -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_PREFIX_PATH=/opt/ros/kinetic -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/gentoo_toolchain.cmake  /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9
loading initial cache file /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Using CATKIN_DEVEL_PREFIX: /var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "3.5.4") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib64/python3.5/site-packages/em.py  
-- Using empy: /usr/lib64/python3.5/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: 0
-- catkin 0.7.11
Traceback (most recent call last):
  File "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/catkin_generated/generate_cached_setup.py", line 12, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named 'catkin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named 'catkin'
CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:186 (safe_execute_process)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build/CMakeFiles/CMakeError.log".
 * ERROR: ros-kinetic/cpp_common-0.6.9::ros-overlay failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_configure
 *   environment, line 4124:  Called ros-cmake_src_configure
 *   environment, line 4027:  Called cmake-utils_src_configure
 *   environment, line 1001:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=ros-kinetic/cpp_common-0.6.9::ros-overlay'`,
 * the complete build log and the output of `emerge -pqv '=ros-kinetic/cpp_common-0.6.9::ros-overlay'`.
 * The complete build log is located at '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/temp/environment'.
 * Working directory: '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build'
 * S: '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9'

>>> Failed to emerge ros-kinetic/cpp_common-0.6.9, Log file:

>>>  '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/temp/build.log'

 * Messages for package ros-kinetic/cpp_common-0.6.9:

 * ERROR: ros-kinetic/cpp_common-0.6.9::ros-overlay failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_configure
 *   environment, line 4124:  Called ros-cmake_src_configure
 *   environment, line 4027:  Called cmake-utils_src_configure
 *   environment, line 1001:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=ros-kinetic/cpp_common-0.6.9::ros-overlay'`,
 * the complete build log and the output of `emerge -pqv '=ros-kinetic/cpp_common-0.6.9::ros-overlay'`.
 * The complete build log is located at '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/temp/environment'.
 * Working directory: '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9_build'
 * S: '/var/tmp/portage/ros-kinetic/cpp_common-0.6.9/work/cpp_common-0.6.9'
```

**Comment by allenh1** [comment]
The output of `equery files ros-kinetic/catkin` has the following directories. They contain no files, but probably shouldn't get created by the install.

```
/opt/ros/kinetic/opt
/opt/ros/kinetic/opt/ros
/opt/ros/kinetic/opt/ros/kinetic
/opt/ros/kinetic/opt/ros/kinetic/lib
/opt/ros/kinetic/opt/ros/kinetic/lib/python2.7
/opt/ros/kinetic/opt/ros/kinetic/lib/python2.7/site-packages
```

**Comment by allenh1** [comment]
Found it! The lib64 directory is the problem. After doing a `mv /opt/ros/kinetic/lib64/python2.7 /opt/ros/kinetic/lib`.

```
/opt/ros/kinetic/lib64
/opt/ros/kinetic/lib64/python2.7
/opt/ros/kinetic/lib64/python2.7/site-packages
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin-0.7.11-py2.7.egg-info
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/__init__.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/builder.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/cmake.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/environment_cache.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/find_in_workspaces.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/init_workspace.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/package_version.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/terminal_color.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/test_results.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/tidy_xml.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/workspace.py
/opt/ros/kinetic/lib64/python2.7/site-packages/catkin/workspace_vcs.py
```

**Comment by awesomebytes** [comment]
Works on my Gentoo Prefix system flawlessly too!

**Pull request merged**
