### PR TITLE
cv_bridge and image_geometry: remove opencv dependencies

### PR DESCRIPTION
**Pull request by MalcolmMielle**
using gcc6, opencv 3.2.0, and ros-lunar works without having to use opencv3 provided by ros.

That was all that was needed to not use the opencv3 given by ros but the one installed on the system :).

### CODE REVIEW

**Comment by MalcolmMielle** [comment]
I don't think so for now since the Gentoo version of opencv appears to be [broken](https://bugs.gentoo.org/636030) for now when using feature2d. I don't know if that's a requirement for some ROS package or not.

**Comment by tfoote** [comment]
I would recommend not swapping out a ROS packaged version for a system version. There's usually a specific reason for the ROS package to have been made rather than use the system version.

**Comment by MalcolmMielle** [comment]
Since gentoo opencv version is somewhat broken that make sense. However, wasn't it because kinetic's Ubuntu version didn't had opencv3 that ROS kinetic had a package for opencv3 ?

**Comment by allenh1** [comment]
> However, wasn't it because kinetic's Ubuntu version didn't had opencv3 that ROS kinetic had a package for opencv3 ?

I'm actually not sure about this. @tfoote/@vrabaud would know better than I.

**Comment by vrabaud** [comment]
OpenCV3 was packaged as it was not in Ubuntu (only appeared in artful).
I try to include critical patches in there (which is pretty rare) and keep opencv_contrib in sync. It could work with your system version, your call.

**Comment by allenh1** [comment]
> I try to include critical patches in there (which is pretty rare) and keep opencv_contrib in sync. It could work with your system version, your call.

I like the idea of having this in here as a "known to work" version instead of relying on the Gentoo packaging to be stable enough. I also have concerns with that version jumping too quickly/linking breaking for ROS packages after an update/etc.

@MalcolmMielle thoughts?

**Comment by MalcolmMielle** [comment]
Yep I agree with having it as a "known to work" version :). Sounds like the best solution because as long as Gentoo opencv is broken that should be blocking in my opinion.
Again opencv3 given by ros didn't compile on my machine and that's why I went that way.

Could we also use a `no_opencv` FLAG, so that if the FLAG is on, we do not compile opencv3 ? I'm not sure how to do this though but could that be an option ?

**Comment by allenh1** [comment]
> Again opencv3 given by ros didn't compile on my machine and that's why I went that way.

@MalcolmMielle which OpenCV is not compiling?

**Comment by MalcolmMielle** [comment]
The OpenCV version given with lunar when compiling with gcc6 #280. The compile problems were fixed upstream so that's why I went that way :)

**Comment by allenh1** [comment]
> The OpenCV version given with lunar when compiling with gcc6 #280.

Right,  I see that now. My bad.

> The compile problems were fixed upstream so that's why I went that way :)

Would you mind attempting to patch the lunar version then with the Gentoo patch? I've been working on some instructions for this that you can find [here.](https://github.com/ros-infrastructure/superflore/blob/bfdc82e4285bf71fac2e1795eaedfada25a7a327/README.md#gentoo)

**Comment by MalcolmMielle** [comment]
No no don't be sorry, it's no problem really :).
The thing is I don't have a patch, I probably wasn't very clear before on what I did, sorry about that. I'm going to try to give more details:

I used opencv 3.2 compiled from source. The Gentoo version, is broken when using feature2d (at least it was last time I tried emerging it). This is the reason why I think this pull request should not make it to the main branch.  However, as soon as OpenCV from the gentoo repo will be fixed, then that should work nicely.
As such, I have no Gentoo patch sadly :(. I've simply used a more recent version of OpenCV itself than the version distributed with lunar.

**Comment by allenh1** [comment]
@MalcolmMielle do you know about the upstream status?

**Comment by MalcolmMielle** [comment]
Of openCV for Gentoo ? Nope :(

**Comment by allenh1** [comment]
> Of openCV for Gentoo ? Nope :(

Haha, ok. I might try it later.

But I wanted to see what you thought about introducing a new ebuild, `virtual/opencv3`  to let both be an option, as opposed to removing the distro specific ones? This way, when either is failing, nobody has to suffer.

**Comment by MalcolmMielle** [comment]
That would be nice indeed. Not sure how to proceed with that thought :)

**Comment by allenh1** [comment]
I believe the usual approach would be to use `RDEPEND` and `IUSE` flags to pick the correct package.
Here's a snippet from `virtual/udev`.

```
IUSE="systemd"

RDEPEND="
	!systemd? ( || ( >=sys-fs/eudev-2.1.1 >=sys-fs/udev-217 ) )
	systemd? ( >=sys-apps/systemd-217:0 )"
```

But it now occurs to me that handling multiple ROS releases might be a pain. Perhaps it would be simpler to change superflore to insert `||( ros-[distro]/opencv3 =media-libs/opencv-3* )` as a dependency instead of just the ROS specific version?

**Comment by MalcolmMielle** [comment]
Maybe but then we would have to control it for every version of ROS. kinetic and lunar work with opencv 3.2 but indigo work with 2.4.

Otherwise yes I guess :). Not too sure how superflore works so that's up to you.

**Pull request closed without merging**
