### PR TITLE
Noetic upgrade

### PR DESCRIPTION
**Pull request by allenh1**
@flabrosse this is your noetic upgrade.

Let me know if this breaks everything.

### CODE REVIEW

**Comment by flabrosse** [comment]
This breaks everything! ;-)  But I was expecting it.  Out of interest, and knowing nothing about the upgrade process, where does the `PYTHON_COMPAT` variable value come from?  At the moment it is set to python versions that are not supported anymore in gentoo.  I can change it and submit a pull request, but it might be better to change that at the source?

Thank you for doing this by the way.

**Comment by allenh1** [comment]
@flabrosse sorry for the delay in response!

The updates come from [superflore](https://github.com/ros-infrastructure/superflore).

In particular, it comes from this function:

https://github.com/ros-infrastructure/superflore/blob/4105ad813803150ff52c671bf507af76b4c69dd2/superflore/generators/ebuild/ebuild.py#L114-L120

I have a branch where I started making things better, but I seem to have failed to push it from my desktop... I'll do that later tonight, and try and update the python version for you.

**Comment by flabrosse** [comment]
What if you accept my PR?  Would the python version be propagated automatically with a superflore update?  I have a few more PR to submit that I have delayed because they depend on the new python versions being in (or the patches might fail).

**Comment by allenh1** [comment]
> What if you accept my PR? Would the python version be propagated automatically with a superflore update? 

Yep -- that's how all the ebuilds get created. It will future-proof things as well (I should say until Gentoo drops support for the python versions we switch to).

**Comment by flabrosse** [comment]
Yeah, it sounds a bit like a high maintenance task...

**Pull request merged**
