### PR TITLE
fixes with repoman

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-2.3.3, Repoman-2.3.1
RepoMan-Options: --force

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
TODO: 
- [ ] set maintainers for all packages (persons or organizations, for the latter we need an email)
- [ ] set copyright license at the top two lines of each ebuild (is needed?)
- [ ] discover the version of the PSF license

**Comment by allenh1** [comment]
From the Gentoo wiki, This is the definition of "maintainer." 

> Provides information about the upstream maintainer. It requires a <name> subtag to be specified, supports an optional <email> subtag and an optional status attribute.

There is one package in there where I am listed a maintainer, which I should remove (I misunderstood the point of this field myself).

I will remove these myself in a few moments.

**Comment by Alessandro-Barbieri** [comment]
You read the maintainer subtag of upstream 

"<upstream> 	This tag contains information about the upstream developers/project. It supports multiple optional subtags: <maintainer>, <changelog>, <doc>, <bugs-to>, and <remote-id>. "

**Comment by allenh1** [comment]
I don't understand what this merge request is for. Could please explain it a little more?

**Comment by allenh1** [comment]
There are a lot of merge conflicts here as well...

**Comment by Alessandro-Barbieri** [comment]
QA with repoman
https://wiki.gentoo.org/wiki/Repoman

**Comment by allenh1** [comment]
I'm sorry. I just don't see a need to merge this.

**Comment by Alessandro-Barbieri** [comment]
I removed the conflicts

**Comment by allenh1** [comment]
I now understand what you were trying to say earlier:

> 	This tag specifies the persons and/or projects responsible for the maintenance of a package. The type attribute must be specified and can be either "person" or "project". There is one required subtag: <email>. It has two optional subtags: <name> and <description>.

There are indeed two maintainer flags.

**Comment by allenh1** [comment]
You have listed yourself as the maintainer of two files. May I be clear: this is not a change I will pull. If you want to discuss being a maintainer, we can do that at a later date. But I will not pull this as we stand currently.

**Comment by allenh1** [comment]
I will need two things from you if you want me to merge this.

1. An explanation for the changes you made, describing why they are necessary. including links to statements regarding deprecation (for book keeping).

2. Remove yourself as maintainer of the two packages. This will not happen in this pull request.

**Comment by Alessandro-Barbieri** [comment]
BTW ebuild maintainer =/= upstream maintainer

an example 
see more here https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer type="person">
    <email>foobar@bar.com</email>
    <name>Foo Bar/name>
  </maintainer>
<upstream>
    <maintainer status="active">
      <email>foobar@foo.com</email>
      <name>Foo Bar</name>
    </maintainer>
    <doc lang="en">http://foo.org/bar/</doc>
    <bugs-to>https://code.google.com/p/bar</bugs-to>
  </upstream>
</pkgmetadata>
```

**Comment by allenh1** [comment]
I understand this. It is rather confusing that we have two maintainer flags. But we do not list ebuild maintainers consistently in this repo, and the size of the repo is not unmanageable, I don't want to start filling in this field.

**Comment by allenh1** [comment]
Thank you very much.

**Comment by allenh1** [comment]
Ok. I found a link to reference for the `$id$` field.

https://bugs.gentoo.org/show_bug.cgi?id=611234

**Comment by Alessandro-Barbieri** [comment]
deprecated $id$
https://bugs.gentoo.org/show_bug.cgi?id=611234
https://bugs.gentoo.org/show_bug.cgi?id=561456

and the repoman fixes are:
RDEPEND.suspect (see link)
KEYWORDS.invalid (see link)
LICENSE.invalid
blank line at the and of file
blank space at the end of line
spaces instead of tabs

other things here
https://dev.gentoo.org/~zmedico/portage/doc/man/repoman.1.html

**Comment by allenh1** [comment]
Thank you for your work.

**Comment by Alessandro-Barbieri** [comment]
`RDEPEND` is for runtime depend
`DEPEND`  id for all dependencies for a package

repoman complains if you put a non runtime dependency (cmake, make, doc stuff) in RDEPEND
because is not strictly necessary after build

**Comment by allenh1** [comment]
Thank you. I will keep this in mind for future pull requests/my own ebuild updates.

**Comment by Alessandro-Barbieri** [comment]
You can check here the latest repoman output
https://gist.github.com/21a3f3adeb4eda8dc798548f0d35a416

**Pull request merged**
