### PR TITLE
Remove extra rosdep dependency in rospack

### PR DESCRIPTION
**Pull request by flabrosse**
Remove one of the two dependencies on the same package, keeping the dev-python one.

### CODE REVIEW

**Comment by allenh1** [comment]
@flabrosse looks good, but please run `repoman manifest` as well! The manifest file needs to be changed as well (since it has a checksum for the ebuild text).

**Comment by flabrosse** [comment]
The only way I could find to submit a PR was to fork and edit manually the file in the Web interface.  For the simple edit that this was, this was OK.  Editing the Manifest in that way is bound to fail, and copy/paste from my local file might well create wrong newlines and such.  I'm willing to have a go (if I can add a file to the PR), but this might not work.

The only other way to create a PR, according to github, is to create a branch, and I don't think I have permissions to do so.

Is there another way?

**Comment by flabrosse** [comment]
I've edited the Manifest, I think correctly.  I don't seem to be able to add that change to the existing PR.  Do I create a new one?

**Comment by allenh1** [comment]
>  I don't seem to be able to add that change to the existing PR. Do I create a new one?

Ah, I think you made this change on GitHub? You'll need to pull down your changes.

```
git clone https://github.com/flabrosse/ros-overlay
git checkout patch-1
```

That should put you on the correct branch, and you should be able to push the change to that branch.

> Do I create a new one?

It's better to have only one PR for this change, so let's just figure out how to get it fixed here instead of filing a new one.

**Comment by flabrosse** [comment]
Didn't know that was creating a branch, as only master is listed as branches.  Done now.  Thanks.

**Pull request merged**
