### PR TITLE
gentoo catkin eclass

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**

### CODE REVIEW

**Comment by allenh1** [comment]
I'd prefer to not use the existing eclass from the Gentoo tree. I'm going to write one in the near future.

This is still a work in progress, but I've got other things to attend to at the moment. I'll pick up with the ebuilds over the weekend.

But, for now, please try out the current ones! I and a few others have been able to install ros-lunar/desktop_full completely!

**Comment by Alessandro-Barbieri** [comment]
mmm ... why reinvent the wheel? You could start by modifying this eclass

**Comment by archenroot** [comment]
I also think better to extend existing class if you don't like something. Stay tight with Gentoo :-)

You can always contact Alexis (https://wiki.gentoo.org/wiki/Project:ROS) and do pull request directly to Gentoo tree.

**Comment by archenroot** [comment]
I got so far with lunar install just one minor exception with dev-python/empy (reported) and will try to finish install over weekend. Good stuff.

**Pull request closed without merging**
